# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import mainapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20170202_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputXls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xls_file', models.FileField(upload_to=b'xlsinput/%Y-%m-%d', validators=[mainapp.validators.validate_excel_extension])),
            ],
        ),
    ]
